config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "saxophones#index"

  resources :saxophones do
    get :my_saxophones, on: :collection, as: "my"
    resources :orders, only: %i[new create]
  end

  get ":user_id/saxophones", to: "saxophones#user_saxophones", as: "user_saxophones"
  get ":user_id/orders", to: "orders#index", as: "user_orders"
  get ":user_id/sales", to: "orders#sales", as: "user_sales"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :saxophone
end

app/models/saxophone.rb
class Saxophone < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  validates :title, :details, :manufacturer, :sax_model, :serial_number, :category, :condition, presence: true
  include AlgoliaSearch

  MANUFACTURERS = ["Antigua", "B&S", "Berg Larsen", "Borgani", "Buffet Crampon", "Cannonball", "Chateau", "Claude Lakey", "Couesnon", "D'Addario", "Dörfler & Jörka", "Eastman", "F. Arthur Uebel", "Gemeinhardt", "Grafton", "Guardala", "H. Couf", "Hanson", "J. Keilwerth", "Jean Baptiste", "Jupiter", "Kanstul", "Keilwerth", "Kessler & Sons", "King", "LA Sax", "Lade", "Mauriat", "P. Mauriat", "Penzel", "Pierret", "Rampone & Cazzani", "Rico", "Rigotti", "Rousseau", "Sakkusu", "Sankyo", "Selmer", "SML", "Steinbach", "Trevor James", "Vandoren", "Vibrato", "Vito", "Warburton", "Weltklang", "Wurlitzer", "Yamaha", "Yanagisawa", "Zonda", "Outro"]
  CATEGORIES = ["Saxofone Soprillo", "Saxofone Sopranino", "Saxofone Soprano", "Saxofone Alto", "Saxofone Tenor", "Saxofone Barítono", "Saxofone Baixo", "Saxofone Contrabaixo"]
  MODELS = ["Selmer Mark VI", "Selmer Balanced Action", "Selmer Super Balanced Action", "Selmer SBA", "Selmer Mark VII", "Selmer Super Action 80", "Selmer Series II", "Selmer Series III", "Selmer Radio Improved", "Conn 6M", "Conn New Wonder Series I", "Conn New Wonder Series II", "Conn Chu Berry", "King Super 20", "King Zephyr", "King Zephyr Special", "Buescher Aristocrat", "Buescher True Tone", "Buescher 400", "Martin Handcraft", "Martin Committee", "Martin Committee II", "Martin Typewriter", "Yamaha YAS-62", "Yamaha YTS-62", "Yamaha YAS-82Z", "Yamaha YTS-82Z", "Yamaha YAS-875", "Yamaha YTS-875", "Yanagisawa S-880", "Yanagisawa T-880", "Yanagisawa S-991", "Yanagisawa T-991", "Keilwerth New King", "Keilwerth Toneking", "Keilwerth SX90", "Buescher 140", "Conn 10M", "Conn Naked Lady", "Martin Handcraft Committee", "Martin Indiana", "Selmer Modele 22", "Selmer Modele 26", "Buescher Big B", "Conn Transitional", "King Voll-True", "Martin Magna", "Selmer Modele 28", "Yamaha YSS-62", "Yamaha YTS-61", "Yanagisawa S-901", "Yanagisawa T-901", "Keilwerth SX90R"]
  CONDITIONS = ["Usado - Excelente estado", "Usado - Bom estado", "Usado - Condição justa", "Revisado", "Danificado - Pode ser consertado", "Danificado - Para peças de reposição"]

  algoliasearch do
    attribute :title, :manufacturer, :category, :sax_model, :condition, :serial_number, :details, :user_id
    attribute :user_name do
      user&.full_name
    end
    searchableAttributes [:title, :manufacturer, :category, :sax_model, :condition, :serial_number, :details, 'user_name']
    queryType 'prefixAll'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  include AlgoliaSearch

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :saxophones
  validates :full_name, :address, presence: true

  algoliasearch do
    attribute :full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  after_action :verify_authorized, except: %i[index sales show user_saxophones], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: %i[index sales show user_saxophones], unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name address photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name address photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @orders = Order.where(user_id: @user.id)
    @saxophones = policy_scope(Saxophone).where(user_id: @user.id)
  end

  def sales
    @user = current_user
    @saxophones = policy_scope(Saxophone)
    @sold_saxophones = @saxophones.where(user_id: @user.id, status: true)
    @sold_orders = []
    if @sold_saxophones.present?
      @sold_saxophones.each do |sax|
        @sold_orders << Order.find_by(saxophone_id: sax.id)
      end
    end
    @sold_orders
  end

  def new
    @order = Order.new
    @saxophone = Saxophone.find(params[:saxophone_id])
    # @user = @saxophone.user
    authorize @order
  end

  def create
    @saxophone = Saxophone.find(params[:saxophone_id])
    @order = Order.new(order_params)
    @saxophone.status = true
    if @order.save && @saxophone.save
      redirect_to user_orders_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
    authorize @order
  end

  private

  def order_params
    params.require(:order).permit(:saxophone_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/saxophones_controller.rb
class SaxophonesController < ApplicationController
  before_action :set_saxophone, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[home index show user_saxophones]

  def index
    @saxophones = policy_scope(Saxophone)
    if params[:category].present?
      @saxophones = @saxophones.where(category: params[:category])
    end
    if params[:query].present?
      @saxophones = Saxophone.algolia_search(params[:query])
    end
  end

  def show
    @saxophone = policy_scope(Saxophone).find(@saxophone.id)
  end

  def user_saxophones
    @user = User.find(params[:user_id])
    @saxophones = policy_scope(Saxophone).where(user_id: @user.id)
  end

  def new
    @saxophone = Saxophone.new
    authorize @saxophone
  end

  def create
    @saxophone = Saxophone.new(saxophone_params)
    @saxophone.user = current_user
    if @saxophone.save
      redirect_to saxophone_path(@saxophone)
    else
      render :new, status: :unprocessable_entity
    end
    authorize @saxophone
  end

  def edit
    authorize @saxophone
  end

  def update
    authorize @saxophone
    @saxophone.update(saxophone_params)
    redirect_to saxophone_path(@saxophone)
  end

  def destroy
    authorize @saxophone
    @saxophone.destroy
    redirect_to user_saxophones_path(current_user), notice: "Anúncio removido.", status: :see_other
  end

  private

  def saxophone_params
    params.require(:saxophone).permit(:title, :price, :manufacturer, :category, :sax_model, :condition, :serial_number, :photo, :details, status: false)
  end

  def set_saxophone
    @saxophone = Saxophone.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_to_currency_br(number)
    number_to_currency(number, :unit => "R$ ", :separator => ",", :delimiter => ".")
  end
  def convert_to_brazilian_date(date)
    date.strftime("%d/%m/%Y")
  end
end

app/helpers/container_helper.rb
module ContainerHelper
  def hide_container?
    current_page?(root_path) || current_page?(saxophones_path)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnColtrane</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="banner-small" style="background-image: linear-gradient(to bottom, rgba(255, 179, 0, 0), rgba(0, 0, 0, 1)), url(https://c0.wallpaperflare.com/preview/857/353/296/music-saxophone-summer-gold.jpg);">
  <div class="container">
    <h1 class="page-title text-start mt-2 mb-2">Meus pedidos</h1> </div>
  </div>
</div>

<div class="container mb-5">
  <% @orders = @orders.sort_by(&:id).reverse %>
  <div class="row flex-column justify-content-center my-5 gap-3">
    <% @orders.each do |order| %>
        <div class="col-12 d-flex gap-3 show-card">

          <div class="picture">
            <% url = "" %>
            <% if order.saxophone.photo.key
                url = cloudinary_url order.saxophone.photo.key
              else
                url = "https://i.pinimg.com/564x/2f/2f/58/2f2f5837fffa68b9b300c99eee660268.jpg"
              end
            %>
            <img src= <%=url%> class="sax-picture" alt="...">
          </div>

          <div class="info m-5">
            <div>
              <h1 class="mb-3"><%= order.saxophone.title %></h1>
              <div class="d-flex gap-3">
                <p><strong> Fabricante: </strong><%= order.saxophone.manufacturer %></p>
                <p><strong> Modelo: </strong><%= order.saxophone.sax_model %></p>
                <p><strong> Categoria: </strong><%= order.saxophone.category %></p>
              </div>
              <p class="card-details"><%= order.saxophone.details %></p>
              <p><strong> Número de série: </strong><%= order.saxophone.serial_number %></p>
              <p><strong> Preço: </strong><%= number_to_currency_br(order.saxophone.price) %></p>
              <p><strong> Estado: </strong><%= order.saxophone.condition %></p>
            </div>
            <%= link_to "Outros produtos deste vendedor",  user_saxophones_path(order.saxophone.user), class: "btn btn-light border rounded-2 shadow-sm w-50" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container mt-5 mb-5">
  <div class="row justify-content-center mt-5 mb-5">
    <div class="col-6">
      <h1>Confirme sua compra</h1>
      <div class="card mt-3" style="width: 100%;">
        <img class="card-image" src=<%=cloudinary_url @saxophone.photo.key%> alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= @saxophone.title %></h5>
          <p class="card-text">Preço: R$ <%= number_to_currency_br(@saxophone.price) %></p>
          <div class="d-flex gap-3">
          <%= simple_form_for [@saxophone, @order], url: saxophone_orders_path(@saxophone), method: :post do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :saxophone_id, value: @saxophone.id %>
            <%= f.submit "Confirmar", class:"btn btn-success text-light shadow-sm"%>
          <% end %>
          <%= link_to "Voltar", saxophone_path(@saxophone), class:"btn btn-secondary shadow-sm" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/sales.html.erb
<div class="banner-small" style="background-image: linear-gradient(to bottom, rgba(255, 179, 0, 0), rgba(0, 0, 0, 1)), url(https://c0.wallpaperflare.com/preview/857/353/296/music-saxophone-summer-gold.jpg);">
  <div class="container">
    <h1 class="page-title text-start mt-2 mb-2">Minhas Vendas</h1> </div>
  </div>
</div>

<div class="container mb-5">
  <% @sold_orders = @sold_orders.sort_by(&:id).reverse %>
  <% @sold_orders.each do |order| %>
    <div class="row justify-content-center mt-5 mb-1">
      <div class="col-12 p-5 d-flex gap-3 show-card">
        <div class="status col-2 m-0 p-0">
          <p class="m-0"><strong> Pedido #</strong><%= order.id %></p>
          <p class="m-0"><strong> Comprado em: </strong><%= convert_to_brazilian_date(order.created_at.to_date) %></p>
        </div>
        <div class="picture">
          <% url = "" %>
          <% if order.saxophone.photo.key
              url = cloudinary_url order.saxophone.photo.key
            else
              url = "https://i.pinimg.com/564x/2f/2f/58/2f2f5837fffa68b9b300c99eee660268.jpg"
            end
          %>
          <img src= <%=url%> class="sax-picture me-2" alt="...">
        </div>

        <div class="info ms-3">
          <h1 class="w-75 mb-3"><%= order.saxophone.title %></h1>
          <div class="d-flex gap-3">
            <p><strong> Fabricante: </strong><%= order.saxophone.manufacturer %></p>
            <p><strong> Modelo: </strong><%= order.saxophone.sax_model %></p>
            <p><strong> Categoria: </strong><%= order.saxophone.category %></p>
          </div>

          <p class="card-details"><%= order.saxophone.details %></p>
          <p><strong> Número de série: </strong><%= order.saxophone.serial_number %></p>
          <p><strong> Preço: </strong><%= number_to_currency_br(order.saxophone.price) %></p>
          <p><strong> Estado: </strong><%= order.saxophone.condition %></p>
          <p><strong> Comprador: </strong><%= order.user.full_name %></p>
          <div class="d-flex gap-3">
        </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/saxophones/_form.html.erb
    <%= simple_form_for(@saxophone) do |f| %>
      <%= f.input :title, label: "Título:" %>
      <%= f.input :details, label: "Descrição:" %>
      <%= f.input :price, label: "Preço:" %>
      <%= f.input :photo, as: :file %>
      <%= f.input :category, collection: Saxophone::CATEGORIES, label: "Categoria:" %>
      <%= f.input :manufacturer, collection: Saxophone::MANUFACTURERS, label: "Fabricante:" %>
      <%= f.input :sax_model, collection: Saxophone::MODELS, label: "Modelo:" %>
      <%= f.input :serial_number, label: "Número de série:" %>
      <%= f.input :condition, collection: Saxophone::CONDITIONS, label: "Condição:" %>
      <%= f.button :submit, request.fullpath == "/saxophones/new" ? "Criar um novo anúncio" : "Editar este anúncio" , class: 'btn btn-secondary mt-3' %>
    <% end %>

app/views/saxophones/edit.html.erb
<div class="banner-small" style="background-image: linear-gradient(to bottom, rgba(255, 179, 0, 0), rgba(0, 0, 0, 1)), url(https://c0.wallpaperflare.com/preview/857/353/296/music-saxophone-summer-gold.jpg);">
  <div class="container">
    <h1 class="page-title text-start mt-4 mb-4">Editar "<%= @saxophone.title %>"</h1>  </div>
  </div>
</div>
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="col-8 card mt-5 mb-5 p-5">
      <%= render "form", saxophone: @saxophone %>
    </div>
  </div>
</div>

app/views/saxophones/new.html.erb
<div class="banner-small" style="background-image: linear-gradient(to bottom, rgba(255, 179, 0, 0), rgba(0, 0, 0, 1)), url(https://c0.wallpaperflare.com/preview/857/353/296/music-saxophone-summer-gold.jpg);">
  <div class="container">
    <h1 class="page-title text-start mt-2 mb-2">Novo anúncio</h1>  </div>
  </div>
</div>
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="col-8 card mt-5 mb-5 p-5">
      <%= render "form", saxophone: @saxophone %>
    </div>
  </div>
</div>

app/views/saxophones/show.html.erb
<div class="banner-small" style="background-image: linear-gradient(to bottom, rgba(255, 179, 0, 0), rgba(0, 0, 0, 1)), url(https://c0.wallpaperflare.com/preview/857/353/296/music-saxophone-summer-gold.jpg);">
  <div class="container">
    <h1 class="page-title text-start mt-2 mb-2">Detalhes</h1> </div>
  </div>
</div>


<div class="container mb-5">

  <div class="row justify-content-center mt-5 mb-5">
    <div class="col-12 d-flex gap-3 show-card">
      <div class="picture">
        <% url = "" %>
        <% if @saxophone.photo.key
            url = cloudinary_url @saxophone.photo.key
          else
            url = "https://i.pinimg.com/564x/2f/2f/58/2f2f5837fffa68b9b300c99eee660268.jpg"
          end
        %>
        <img src= <%=url%> class="sax-picture" alt="...">
      </div>

      <div class="info m-5">
        <div>
          <h1 class="mb-3"><%= @saxophone.title %></h1>
          <div class="d-flex gap-3">
            <p><strong> Fabricante: </strong><%= @saxophone.manufacturer %></p>
            <p><strong> Modelo: </strong><%= @saxophone.sax_model %></p>
            <p><strong> Categoria: </strong><%= @saxophone.category %></p>
          </div>
          <p class="card-details"><%= @saxophone.details %></p>
          <p><strong> Número de série: </strong><%= @saxophone.serial_number %></p>
          <p><strong> Preço: </strong><%= number_to_currency_br(@saxophone.price) %></p>
          <p><strong> Estado: </strong><%= @saxophone.condition %></p>
        </div>
        <div>
          <% if @saxophone.user != current_user %>
            <%= link_to "Comprar", new_saxophone_order_path(@saxophone), class: "btn btn-primary shadow-sm" %>
          <% end %>

          <%= link_to "Outros produtos deste vendedor",  user_saxophones_path(@saxophone.user), class: "btn btn-light border rounded-2 shadow-sm" %>

          <% if policy(@saxophone).edit? %>
            <%= link_to "Editar", edit_saxophone_path(@saxophone), class: "btn btn-secondary" %>
          <% end %>
          <%= link_to "Remover", saxophone_path(@saxophone), data: {turbo_method: :delete, turbo_confirm: 'Você tem certeza?'}, class: "btn btn-danger text-light" if policy(@saxophone).destroy?%>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/saxophones/user_saxophones.html.erb
<div class="banner-small" style="background-image: linear-gradient(to bottom, rgba(255, 179, 0, 0), rgba(0, 0, 0, 1)), url(https://c0.wallpaperflare.com/preview/857/353/296/music-saxophone-summer-gold.jpg);">
  <div class="container">
    <h1 class="page-title text-start mt-4 mb-4">Saxofones de <%= @user.full_name %></h1>  </div>
  </div>
</div>

<div class="container mt-4 mb-5">
  <div class="cards-add p-2 mb-4">
  <% @saxophones = @saxophones.sort_by(&:id).reverse %>
  <% @saxophones.each do |sax| %>
    <% if sax.status != true %>
      <div class="card-category-add">

        <% url = "" %>
        <% if sax.photo.key
            url = cloudinary_url sax.photo.key
          else
            url = "https://i.pinimg.com/564x/2f/2f/58/2f2f5837fffa68b9b300c99eee660268.jpg"
          end
        %>

        <div class="img-container-card">
          <img src= <%=url%> alt="sax pic">
        </div>

        <div class="card-info">
          <div class="d-flex gap-3 mb-2 justify-content-between">
            <p class="card-title-add pt-2"><%= sax.title %></p>
            <% sax_url = "" %>
            <% if sax.user.photo.key
                sax_url = cloudinary_url sax.user.photo.key
              else
                sax_url = "https://cdn-icons-png.flaticon.com/512/6386/6386976.png"
              end
            %>
            <%= link_to user_saxophones_path(sax.user) do %>
            <img src="<%=sax_url%>" class="rounded-circle avatar-image" alt="...">
            <% end %>
          </div>

          <div class="d-flex gap-3 mb-2">
            <p class="card-title-text" style="color:#bf4800"><%= sax.manufacturer %></p>
            <p class="card-title-text" style="color:#bf4800"><%= sax.sax_model %></p>
          </div>
          <p class="card-details"><%= "#{sax.details[0..40]}..." %></p>
          <div class="d-flex justify-content-between align-items-center">
            <p class="card-price"><%= number_to_currency_br(sax.price) %></p>
            <div class="d-flex gap-3">
              <%= link_to saxophone_path(sax), class:"btn-details" do %>
                <i class="fa-solid fa-magnifying-glass"></i>
              <% end %>
              <% if policy(sax).edit? %>
                <%= link_to edit_saxophone_path(sax), class: "btn-edit" do %>
                  <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
              <% end %>
              <% if policy(sax).destroy? %>
                <%= link_to saxophone_path(sax), data: {turbo_method: :delete, turbo_confirm: 'Você tem certeza?'}, class: "btn-delete text-decoration-none" do %>
                  <i class="fa-solid fa-trash-can"></i></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container footer-flex">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div>
       Todos os direitos reservados. | Política de Privacidade | Termos de Uso
    </div>
    <div class="footer-copyright">
      © 2023 EnColtrane
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between">
      <%= link_to saxophones_path, class: "navbar-brand" do %>
        <%= image_tag "https://static.thenounproject.com/png/264538-200.png" %>
      <% end %>
       <%= link_to saxophones_path, class: "navbar-brand" do %>
        <p class="navbar-brand-name">EnColtrane</p>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Criar novo anúncio", new_saxophone_path, class: "nav-link" %>
          </li>
          <li class="nav-item active ms-4">
            <%= link_to "Home", saxophones_path, class: "nav-link" %>
          </li>
          <li class="ms-4">
            Olá, <%= current_user.full_name%>
          </li>
          <li class="nav-item dropdown ms-4">
            <% if current_user.photo.key %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle" , id: "navbarDropdown", data: { bs_toggle: "dropdown" }, "aria-haspopup": true, "aria-expanded": false, height: 50, width: 50, crop: :fill%>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/dfjub9qt4/image/upload/v1685459177/user_png.png", class: "avatar dropdown-toggle" , id: "navbarDropdown", data: { bs_toggle: "dropdown" }, "aria-haspopup": true, "aria-expanded": false, height: 50, width: 50, crop: :fill%>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Meus items", user_saxophones_path(current_user.id), class: "dropdown-item" %>
              <%= link_to "Pedidos", user_orders_path(current_user), class: "dropdown-item" %>
              <%= link_to "Vendas", user_sales_path(current_user), class: "dropdown-item" %>
              <%= link_to "Editar Perfil",edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Criar Conta", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>